package pkgfinal.java.swing.app;

import java.awt.*;
import javax.swing.*;
import java.awt.event.*;


/**
 *
 * @author rsprigge
 */
public class Calculator extends javax.swing.JFrame implements ActionListener {

    
    boolean[] operations = new boolean[4];
    double[] temps = {0, 0};
    
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        
        for(int i = 0; i < 4; i++)
            operations[i] = false;

    }
    
    
    public void clear() {
        try {
            jTextArea1.setText("");
            for(int i = 0; i < 4; i++)
                operations[i] = false;
            for(int i = 0; i < 2; i++)
                temps[i] = 0;
        } catch(NullPointerException e) {  
        }
    }
    
    
    
    public void result() {
        double result = 0;
        temps[1] = Double.parseDouble(jTextArea1.getText());
        String temp0 = Double.toString(temps[0]);
        String temp1 = Double.toString(temps[1]);
        
        try {
            if(operations[2] == true)
                result = temps[0] * temps[1];
            else if(operations[3] == true)
                result = temps[0] / temps[1];
            else if(operations[0] == true)
                result = temps[0] + temps[1];
            else if(operations[1] == true)
                result = temps[0] - temps[1];
            jTextArea1.setText(Double.toString(result));
            for(int i = 0; i < 4; i++)
                operations[i] = false;
        } catch(NumberFormatException e) {
        }
    }
    
    
    public void actionPerformed(ActionEvent perform) {
        if(perform.getSource() == jButton1)
            jTextArea1.append("7");
        if(perform.getSource() == jButton2)
            jTextArea1.append("8");
        if(perform.getSource() == jButton3)
            jTextArea1.append("9");
        if(perform.getSource() == jButton8) {
            //add function[0]
            temps[0] = Double.parseDouble(jTextArea1.getText());
            operations[0] = true;
            jTextArea1.setText("");
        }
        if(perform.getSource() == jButton5)
            jTextArea1.append("4");
        if(perform.getSource() == jButton6)
            jTextArea1.append("5");
        if(perform.getSource() == jButton7)
            jTextArea1.append("6");
        if(perform.getSource() == jButton12) {
            //subtract function[1]
            temps[0] = Double.parseDouble(jTextArea1.getText());
            operations[1] = true;
            jTextArea1.setText("");
        }
        if(perform.getSource() == jButton9)
            jTextArea1.append("1");
        if(perform.getSource() == jButton10)
            jTextArea1.append("2");
        if(perform.getSource() == jButton11)
            jTextArea1.append("3");
        if(perform.getSource() == jButton16) {
            //multiply function[2]
            temps[0] = Double.parseDouble(jTextArea1.getText());
            operations[2] = true;
            jTextArea1.setText("");
        }
        if(perform.getSource() == jButton14)
            jTextArea1.append(".");
        if(perform.getSource() == jButton15) {
            //divide function[3]
            temps[0] = Double.parseDouble(jTextArea1.getText());
            operations[3] = true;
            jTextArea1.setText("");
        }
        if(perform.getSource() == jButton4)
            clear();
        if(perform.getSource() == jButton17)
            result();
        if(perform.getSource() == jButton13)
            jTextArea1.append("0");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(1);
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.setEditable(false);
        jTextArea1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 498, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setLayout(new java.awt.GridLayout(5, 4));

        jButton1.setText("7");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.addActionListener(this);

        jButton2.setText("8");
        jPanel2.add(jButton2);
        jButton2.addActionListener(this);

        jButton3.setText("9");
        jPanel2.add(jButton3);
        jButton3.addActionListener(this);

        jButton4.setText("C");
        jPanel2.add(jButton4);
        jButton4.addActionListener(this);

        jButton5.setText("4");
        jPanel2.add(jButton5);
        jButton5.addActionListener(this);

        jButton6.setText("5");
        jPanel2.add(jButton6);
        jButton6.addActionListener(this);

        jButton7.setText("6");
        jPanel2.add(jButton7);
        jButton7.addActionListener(this);

        jButton8.setText("+");
        jPanel2.add(jButton8);
        jButton8.addActionListener(this);

        jButton9.setText("1");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);
        jButton9.addActionListener(this);

        jButton10.setText("2");
        jPanel2.add(jButton10);
        jButton10.addActionListener(this);

        jButton11.setText("3");
        jPanel2.add(jButton11);
        jButton11.addActionListener(this);

        jButton12.setText("-");
        jPanel2.add(jButton12);
        jButton12.addActionListener(this);

        jButton13.setText("0");
        jPanel2.add(jButton13);
        jButton13.addActionListener(this);

        jButton14.setText(".");
        jPanel2.add(jButton14);
        jButton14.addActionListener(this);

        jButton15.setText("/");
        jPanel2.add(jButton15);
        jButton15.addActionListener(this);

        jButton16.setText("*");
        jPanel2.add(jButton16);
        jButton16.addActionListener(this);

        jButton17.setText("=");
        jPanel2.add(jButton17);
        jButton17.addActionListener(this);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 490, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

//    @Override
//    public void actionPerformed(ActionEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
}
